const actionTypes = {
  WIDGET_CREATE: 'WIDGET_CREATE',
  WIDGET_DELETE: 'WIDGET_DELETE',
  WIDGET_RESIZE: 'WIDGET_RESIZE',
  WIDGET_CONNECT: 'WIDGET_CONNECT',
  WIDGETS_CLEAR: 'WIDGETS_CLEAR',
  WIDGET_PLACE: 'WIDGET_PLACE',
  WIDGET_MOVE: 'WIDGET_MOVE',
  REPORT_LOAD: 'REPORT_LOAD',
  REPORT_SAVE: 'REPORT_SAVE',
};

export default actionTypes;
